app:
  env: sit

debug: false

spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/learning
    username: learning
    password: learning
    learning:
      url: jdbc:mysql://localhost:3306/learning
      username: learning
      password: learning

---
spring:
  profiles: prod

app:
  env: prod

debug: false