app:
  env: sit

debug: false

spring:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/learning
    username: learning
    password: learning
    learning:
      url: jdbc:mysql://localhost:3306/learning
      username: learning
      password: learning
    common:
      url: jdbc:mysql://localhost:3306/common
      username: common
      password: common
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
---
spring:
  profiles: prod

app:
  env: prod

debug: false