app:
  env: sit

debug: true

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/learning
    username: learning
    password: learning

---
spring:
  profiles: prod

app:
  env: prod

debug: false